x = int(10)
y = int(99.99)
z = int("3")
print(x)
print(y)
print(z)
print("--------------------------------")
p = float(1)
q = float(89.5)
r = float("5")
s = float("8.4")
print(p)
print(q)
print(r)
print(s)
print("--------------------------------")
a = str("s5")
b = str(5)
c = str(5.5)
print(a)
print(b)
print(c)
print(type(a))
print(type(b))
print(type(c))
print("--------------------------------")
